name: "Check valid slides"
description: "Check for valid slides in the pull request"
author: "Philip Hamelink and Thomas Srour"

inputs:
  token:
    description: "GitHub Secret Token used to comment on PR"
    required: false

runs:
  using: "node16"
  main: "dist/index.js"
